spring:
  profiles:
    active : dev

server:
  port: 8089

---
#本地开发环境配置
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:test
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  file: test.log
